### PR TITLE
Feature/jordan/update to internal parity

### PR DESCRIPTION
**Pull request by jordan-moore**

### CODE REVIEW

**Comment by troyibm** [comment]
You added the word "Personal" to the description on the readme.  While the org name is Watson-Personal-Assistant, we refer to ourselves in docs and in org title as Watson Assistant Solutions, so I think you should remove "Personal" and add "Solutions".

**Comment by troyibm** [comment]
The link in the README on where to get the slack API tokens leads to a page that discusses "legacy" api tokens which is "an older method of adding integrations".  I'm wondering if it's okay to use the newer approach?  If so, we should change the link.

**Comment by troyibm** [comment]
I'm getting this error..

   2018-08-29T14:48:08.59-0500 [APP/PROC/WEB/0] ERR 2018-08-29 19:48:08,589 - root - WARNING -
   2018-08-29T14:48:08.59-0500 [APP/PROC/WEB/0] ERR Error: TypeError Problem reading Max Message Cache Size Integer from environment variables. MAX_MESSAGE_CACHE was set to 1000. Arguments:
   2018-08-29T14:48:08.59-0500 [APP/PROC/WEB/0] ERR ("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",)
   2018-08-29T14:48:08.79-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2018-08-29T14:48:08.79-0500 [APP/PROC/WEB/0] ERR   File "bot.py", line 24, in <module>
   2018-08-29T14:48:08.79-0500 [APP/PROC/WEB/0] ERR     BOT_USER_ID = slack_client.api_call('auth.test')['user_id']
   2018-08-29T14:48:08.79-0500 [APP/PROC/WEB/0] ERR KeyError: 'user_id'

**Comment by troyibm** [comment]
I do think we should change not to use legacy tokens..

image

**Comment by troyibm** [comment]
Fixed my error above.  I think you need to add back the WA_USER_ID variable in the .env.sample.

**Comment by troyibm** [comment]
So, I think we should make the following changes...

1) I didn't want to create a env vars one at a time for 15 variables, so instead I commented out the check for if 'VCAP_SERVICES' is in os.environment and just unindented line 38 and 41.  The .env file is pushed to bluemix, so the code can read it and use it

2) I used the -m flag to the bluemix push command since if not specified bluemix will create the app with 1028M of memory which is probably overkill and more likely to fail.  I used `-m 256M` in the `cf app push` command.  Also, I think the bx command is now ibmcloud so you should probably change that as well.

Would be nice to change the term 'BOT_ID' confusing as I wasn't sure if that was the same as Bot Name when setting up the bot in slack UI.

**Review by troyibm — CHANGES_REQUESTED** [review]
see my comment above

**Comment by jordan-moore** [comment]
Opening new feature branch to tackle most of the above

**Pull request closed without merging**
